# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afc268d1fa58f434819f6ab1d85d55b7d7601d1c7f63f7edebec665b26dca977321656eda2c2a3161125337dc4c917a1f2b1697dbc308f927130465224a6ffac

test:
  secret_key_base: 2ed8e17a774eb34dca205d532e7c7c3a04427106289f1572a13c8725dfc6edfb5ed584c47fd87aac8b559efce14186b0c0a915c99b8951ed74701e9e601460c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
